# Generated by Django 4.1 on 2022-09-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_tododay_todos_delete_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tododay',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
